### ISSUE TITLE
SyntaxError: Unexpected token import 报错解决方法

### ISSUE THREAD

**Issue by jackieli123723** [jackieli123723/jackieli123723.github.io#51]
## babel-core/register 解决 import xx from xx 

```
import Koa from 'koa';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

#### 传入参数
```
require("babel-core/register")({
  "presets": [
    ["env", {
      "targets": {
        "node": true
      }
    }]
  ]
});
require("./app.js");

或者

require('babel-core/register')({
  'presets': [
    'stage-3',
    ["latest-node", { "target": "current" }]
  ]
})
require('./app')
```

#### 简洁版本
```
require('babel-core/register');
require('./app.js');


```

## 注意

```
require('babel-core/register') 可以用 node --harmony_async_await 代替 从7.6.0开始 已经支持aysnc 和 await
```

**Comment by jackieli123723** [comment]
```


var cmd=require('node-cmd');
cmd.run('npm start');


使用pm2 start blog.js即可正常访问

```

**Comment by jackieli123723** [comment]
## ts-node ??

```

```


vs

```js
  "dependencies": {
    "babel-polyfill": "^6.16.0",
    "cors": "^2.8.1"
  },
  "devDependencies": {
    "babel": "^6.5.2",
    "babel-cli": "^6.18.0",
    "babel-loader": "^6.2.7",
    "babel-preset-es2015": "^6.18.0",
    "express": "^4.14.0"
  },
  "scripts": {
    "start": "babel-node server.js"
  },
```
